# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 17:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_useralbum_usersong'),
    ]

    operations = [
        migrations.CreateModel(
            name='myplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mysong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Song')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='useralbum',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersong',
            name='useralbum',
        ),
        migrations.DeleteModel(
            name='userAlbum',
        ),
        migrations.DeleteModel(
            name='userSong',
        ),
    ]
